# Generated by Django 3.1.1 on 2020-09-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcatalogue',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='productcatalogue',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
