# Generated by Django 3.1.1 on 2020-09-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0003_auto_20201001_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcatalogue',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
